package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"example/graph/model"
	"fmt"

	"github.com/google/uuid"
)

func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	
	var createdByUser *model.User


	for _,user := range r.UserData {
		if  user.ID == input.UserID {
			createdByUser = user
			break
		}
	}

	if createdByUser == nil {
		return nil,fmt.Errorf("Could not find that user")
	}

	createdTodo := &model.Todo{
		ID:   uuid.NewString(),
		Text: input.Text,
		Done: false,
		User: createdByUser,
	}

	r.TodoData = append(r.TodoData, createdTodo)
	
	return createdTodo , nil
}

// Query resolvers
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return r.TodoData, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.UserData, nil
}

// Friends is the resolver for the friends field.
func (r *userResolver) Friends(ctx context.Context, u *model.User) ([]*model.User, error) {
	return []*model.User{
		{
			ID: "1",
			Name: "Jamari",
		},
	},nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
